
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/supraja-saravanan/devops-automation1.git
    targetRevision: HEAD
    path: devops-automation1
  destination:
    server: https://kubernetes.default.svc
    namespace: appargo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

